### ISSUE TITLE
FileNotFoundError for CataclysmQuery.yml

### ISSUE THREAD

**Issue by rtwfroody** [Mattie/cataclysm#1]
```
tnewsome@compy-linux:~/projects/cataclysm-test$ cat hello.py 
#!/bin/env python3

from cataclysm import doom

print(doom.turn_upside_down("Hello, Australia!"))
tnewsome@compy-linux:~/projects/cataclysm-test$ python3 hello.py 
Traceback (most recent call last):
  File "/home/tnewsome/projects/cataclysm-test/hello.py", line 5, in <module>
    print(doom.turn_upside_down("Hello, Australia!"))
  File "/home/tnewsome/.local/lib/python3.10/site-packages/cataclysm/doomed.py", line 66, in magic_method_creator
    code = self._conjure_code(calling_function_name, code_signature, formatted_info)
  File "/home/tnewsome/.local/lib/python3.10/site-packages/cataclysm/doomed.py", line 178, in _conjure_code
    fresh_code = self._generate_fresh_code(formatted_info)
  File "/home/tnewsome/.local/lib/python3.10/site-packages/cataclysm/doomed.py", line 147, in _generate_fresh_code
    ai_query = Petition.objects.get("CataclysmQuery")
  File "/home/tnewsome/.local/lib/python3.10/site-packages/datafiles/manager.py", line 78, in get
    instance.datafile.load(_first_load=True)
  File "/home/tnewsome/.local/lib/python3.10/site-packages/datafiles/mapper.py", line 184, in load
    data = formats.deserialize(self.path, self.path.suffix)
  File "/home/tnewsome/.local/lib/python3.10/site-packages/datafiles/formats.py", line 121, in deserialize
    with path.open("r") as file_object:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/tnewsome/projects/cataclysm-test/datafiles/plunkylib/petition/CataclysmQuery.yml'
tnewsome@compy-linux:~/projects/cataclysm-test$ 
```

Creating the directories didn't help. Creating an empty file didn't help either. Then it complains about the .txt version. And then the same for prompts, etc. There must be something wrong with my setup. Surely those files would get auto-generated?

**Comment by Mattie** [comment]
@rtwfroody Hiya-- did you run the `cataclysm init` from the CLI inside the /home/tnewsome/projects/cataclysm-test directory? You'll need to do that first to get it to copy the initial datafiles into place for the project to experiment with.

If init isn't working, you can also get those files from the default_files subdirectory from the git repo. Let me know if that doesn't sort things out for you!

In the end you want to see these subdirectories from the repo's default_files with their YAML underneath your project directory:
        f"datafiles/plunkylib/petition/CataclysmQuery.yml",
        f"datafiles/plunkylib/prompts/CataclysmPrompt.yml",
        f"datafiles/plunkylib/params/CataclysmLLMParams.yml",
        f"datafiles/plunkylib/params/CataclysmLLMParams_3-5.yml",
(along with a .env file with your OpenAI API key following the "env.template.cataclysm" template)

**Comment by Mattie** [comment]
I could make it automatically set that stuff up if it's not found, but I'm a little nervous copying junk to the local subdirectory if the user didn't explicitly seek it. Hmmm...

**Comment by rtwfroody** [comment]
I did not, because reading is hard. :roll_eyes: 

Given the nature of this extension, copying stuff into the local directory (or better, the directory the script lives in) is probably OK. Note that it had created an empty logs directory even without running `cataclysm init`.

With the init it worked perfectly:
```tnewsome@compy-linux:~/projects/cataclysm-test$ python3 hello.py 
2023-03-31 14:54:20.130 | DEBUG    | cataclysm.doomed:_conjure_code:182 - Doomed code:
# Original calling signature: doom.turn_upside_down("Hello, Australia!")
## import string
## 
## def turn_upside_down(input_str):
##     upside_down_mapping = {
##         'A': '∀', 'B': '𐐒', 'C': 'Ɔ', 'D': 'ᗡ', 'E': 'Ǝ', 'F': 'Ⅎ', 'G': '⅁', 'H': 'H', 'I': 'I', 'J': 'ſ', 'K': '⋊', 'L': '˥', 'M': 'W', 'N': 'N', 'O': 'O', 'P': 'Ԁ', 'Q': 'Ό', 'R': 'ᴚ', 'S': 'S', 'T': '⊥', 'U': '∩', 'V': 'Λ', 'W': 'M', 'X': 'X', 'Y': '⅄', 'Z': 'Z',
##         'a': 'ɐ', 'b': 'q', 'c': 'ɔ', 'd': 'p', 'e': 'ǝ', 'f': 'ɟ', 'g': 'ƃ', 'h': 'ɥ', 'i': 'ᴉ', 'j': 'ɾ', 'k': 'ʞ', 'l': 'l', 'm': 'ɯ', 'n': 'u', 'o': 'o', 'p': 'd', 'q': 'b', 'r': 'ɹ', 's': 's', 't': 'ʇ', 'u': 'n', 'v': 'ʌ', 'w': 'ʍ', 'x': 'x', 'y': 'ʎ', 'z': 'z',
##         '0': '0', '1': '⇂', '2': 'ᘔ', '3': 'Ɛ', '4': 'ᔭ', '5': 'ϛ', '6': '9', '7': 'ㄥ', '8': '8', '9': '6',
##         '.': '˙', ',': "'", '?': '¿', '!': '¡', '(': ')', ')': '(', '[': ']', ']': '[', '{': '}', '}': '{', '<': '>', '>': '<', '&': '⅋', '_': '‾', ';': '؛', ' ': ' '
##     }
## 
##     output_str = ''.join(upside_down_mapping.get(char, char) for char in reversed(input_str))
##     return output_str
## 
## _exec_return_values = turn_upside_down(args_in[0])
¡ɐᴉlɐɹʇsn∀ 'ollǝH
```

What a time to be alive...
