### ISSUE TITLE
Keep getting index out or range error

### ISSUE THREAD

**Issue by virobit** [Mattie/cataclysm#13]
Love this concept, been trying the examples and few of my own tests with it, each time I get the following error: 

Cataclysmic Hangman

Traceback (most recent call last):
  File "/mnt/cataclysm-master/examples/hangman/hangman/__main__.py", line 26, in <module>
    main()
  File "/mnt/cataclysm-master/examples/hangman/hangman/__main__.py", line 11, in main
    word = doom.randomly_select_word_for_hangman_game(wordlist=doom.get_hangman_complex_wordlist())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.pyenv/versions/3.11.3/lib/python3.11/site-packages/cataclysm/doomed.py", line 66, in magic_method_creator
    code = self._conjure_code(calling_function_name, code_signature, formatted_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.pyenv/versions/3.11.3/lib/python3.11/site-packages/cataclysm/doomed.py", line 178, in _conjure_code
    fresh_code = self._generate_fresh_code(formatted_info)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.pyenv/versions/3.11.3/lib/python3.11/site-packages/cataclysm/doomed.py", line 154, in _generate_fresh_code
    fresh_code = completion_result.text.split("#|~~\n")[1]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by virobit** [comment]
Here is what chatgpt says about the error: It seems like the error is caused by the fact that the expected string "#|~~\n" is not found in the completion_result.text. When you try to access the second element of the list (index 1) after splitting, it raises an IndexError because the list has only one element.
To fix this issue, you can add a check to ensure that the expected string is present in the completion_result.text. If it's not found, you can return an appropriate error message or handle the situation accordingly. Here's an example of how you can modify the code:
python

Copy

def _generate_fresh_code(self, formatted_info):
    """Generate fresh code using OpenAI given formatted_info to use in the prompt."""
    # use plunkylib for the query
    ai_query = Petition.objects.get("CataclysmQuery")
    ai_query.load_all()
    args = {}
    args['arg1'] = formatted_info
    # we're not an async function, so we can't use await, so we can have asyncio run the function for us
    completion_result, adj_prompt_text = asyncio.run(petition_completion2(petition=ai_query, additional=args, content_filter_check=False))
    # take the resulting text and check if the expected string is present
    split_result = completion_result.text.split("#|~~\n")
    if len(split_result) > 1:
        fresh_code = split_result[1]
        return fresh_code
    else:
        # Handle the situation when the expected string is not found
        # You can return an error message or handle it in any other way you prefer
        return "Error: Expected string not found in the completion result."
This way, you can avoid the IndexError and handle the situation when the expected string is not found in the completion_result.text.

**Comment by virobit** [comment]
This issue went away when i got gpt4 api access and switched over to that model.
